name = "SHA3"
uuid = "024dbb13-cbdc-4f8e-9218-0cc7169443be"
authors = ["Heptazhou <zhou at 0h7z dot com>"]

[compat]
julia = "â‰¥ 1.0.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
